FROM node:latest
RUN apt update -y
WORKDIR /data/
COPY serviceProvider.js serviceProvider.js
COPY FairDelegation1_sol_EllipticCurve.bin FairDelegation1_sol_EllipticCurve.bin
COPY FairDelegation1_sol_FairDelegation1.bin FairDelegation1_sol_FairDelegation1.bin
COPY FairDelegation1_sol_EllipticCurve.abi FairDelegation1_sol_EllipticCurve.abi
COPY FairDelegation1_sol_FairDelegation1.abi FairDelegation1_sol_FairDelegation1.abi
COPY util.js util.js
RUN npm install ws-await web3-eth-contract eth-crypto web3
EXPOSE 8002
ENTRYPOINT ["node", "serviceProvider.js"]
