version: '3.9'

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"

services:
    blockchain:
        build: .
        container_name: blockchain
        ports:
            - '8545:8545'
        expose:
            - '8545'
        networks:
            app_net:
                ipv4_address: 172.16.238.45
