FROM node:latest
WORKDIR /data/
COPY customer.js customer.js
COPY FairDelegation3_sol_EllipticCurve.bin FairDelegation3_sol_EllipticCurve.bin
COPY FairDelegation3_sol_FairDelegation3.bin FairDelegation3_sol_FairDelegation3.bin
COPY FairDelegation3_sol_EllipticCurve.abi FairDelegation3_sol_EllipticCurve.abi
COPY FairDelegation3_sol_FairDelegation3.abi FairDelegation3_sol_FairDelegation3.abi
COPY util.js util.js
RUN npm install ws-await web3-eth-contract eth-crypto web3
EXPOSE 8001
ENTRYPOINT ["node", "customer.js"]
